### ISSUE TITLE
tests are failing on alpine / musl based distributions

### ISSUE THREAD

**Issue by hrefhref** [evadne/gen_magic#18]
As the title says. Happens on this branch or the one in #13. In this repo develop it fails silently, in #13 it fails with `Unknown: 0: using regular magic file [binary gargabe]`. I wonder if this related to #16. Stay tuned for more details..

**Comment by hrefhref** [comment]
Tried by removing the setup_options calls and just initializing magic with `NULL` as database (for the default) -- and it works now fine on Alpine. So definitely related with #16

**Comment by evadne** [comment]
The version tested did not cope well with warnings printed when using uncompiled magic… Which was fixed in 1.0.1 onwards.

**Comment by evadne** [comment]
Hi, I have added a specific Dockerfile that addresses this scenario FYI

(The underlying issue might have been fixed earlier)

https://github.com/evadne/gen_magic/commit/e2331a6871ca7ebdb3f7435ad3106a1816826e9a
