### ISSUE TITLE
Failing test in ci

### ISSUE THREAD

**Issue by joaothallis** [evadne/gen_magic#9]
Without modification of develop branch, one test is failing in ci.

Build: https://travis-ci.org/github/evadne/gen_magic/jobs/684948387

**Comment by hrefhref** [comment]
The current code uses `magic_error` which apparently can return very random text or just no text. My PR #13 fixes this by using `magic_errno`.

**Comment by evadne** [comment]
I think this is resolved on the develop branch but if not please reopen. Thanks!
